/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2015-12-29 20:52:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class appointments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/lib/jstl-1.2.jar", Long.valueOf(1364136296000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("        <title>Metro Medi Care </title>\r\n");
      out.write("\r\n");
      out.write("        <!-- Bootstrap core CSS -->\r\n");
      out.write("\r\n");
      out.write("        <link href=\"resource/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"resource/fonts/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"resource/css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom styling plus plugins -->\r\n");
      out.write("        <link href=\"resource/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"resource/css/icheck/flat/green.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <link href=\"resource/css/calendar/fullcalendar.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"resource/css/calendar/fullcalendar.print.css\" rel=\"stylesheet\" media=\"print\">\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resource/js/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"nav-md\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main_container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 left_col\">\r\n");
      out.write("                <div class=\"left_col scroll-view\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"navbar nav_title\" style=\"border: 0;\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"site_title\"> <span>Metro Medi Care</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- menu prile quick info -->\r\n");
      out.write("                    <div class=\"profile\">\r\n");
      out.write("                        <div class=\"profile_pic\">\r\n");
      out.write("                            <img src=\"resource/images/user_icon.png\" alt=\"...\" class=\"img-circle profile_img\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profile_info\">\r\n");
      out.write("                            <span>Welcome,</span>\r\n");
      out.write("                            <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /menu prile quick info -->\r\n");
      out.write("\r\n");
      out.write("                    <br />\r\n");
      out.write("\r\n");
      out.write("                    <!-- sidebar menu -->\r\n");
      out.write("                    \r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- /sidebar menu -->\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- top navigation -->\r\n");
      out.write("            \r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topbar.jsp", out, false);
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- /top navigation -->\r\n");
      out.write("\r\n");
      out.write("                <!-- page content -->\r\n");
      out.write("                <div class=\"right_col\" role=\"main\">\r\n");
      out.write("                    <div class=\"\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"page-title\">\r\n");
      out.write("                            <div class=\"title_left\">\r\n");
      out.write("                                <h3>\r\n");
      out.write("                                    Appointments\r\n");
      out.write("                                    <small>\r\n");
      out.write("                                        Doctor/Patient\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                </h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"title_right\">\r\n");
      out.write("                                <div class=\"col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search\">\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                                        <span class=\"input-group-btn\">\r\n");
      out.write("                                            <button class=\"btn btn-default\" type=\"button\">Go!</button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <div class=\"x_panel\">\r\n");
      out.write("                                    <div class=\"x_title\">\r\n");
      out.write("                                        <h2>Appointment Details </h2>\r\n");
      out.write("                                        <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                                            <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li class=\"dropdown\">\r\n");
      out.write("                                                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                                                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                                                    <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                    <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                                                    </li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                            <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                                            </li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                        <div class=\"clearfix\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"x_content\">\r\n");
      out.write("\r\n");
      out.write("                                        <div id='calendar'></div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- footer content -->\r\n");
      out.write("                    \r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- /footer content -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Start Calender modal -->\r\n");
      out.write("                <div id=\"CalenderModalNew\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("                                <h4 class=\"modal-title\" id=\"myModalLabel\">New Appointment Entry</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <div id=\"testmodal\" style=\"padding: 5px 20px;\">\r\n");
      out.write("                                    <form id=\"antoform\" class=\"form-horizontal calender\" role=\"form\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label class=\"col-sm-3 control-label\">Title</label>\r\n");
      out.write("                                            <div class=\"col-sm-9\">\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label class=\"col-sm-3 control-label\">Description</label>\r\n");
      out.write("                                            <div class=\"col-sm-9\">\r\n");
      out.write("                                                <textarea class=\"form-control\" style=\"height:55px;\" id=\"descr\" name=\"descr\"></textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-default antoclose\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary antosubmit\">Save changes</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"CalenderModalEdit\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\r\n");
      out.write("                                <h4 class=\"modal-title\" id=\"myModalLabel2\">Edit Appointment Entry</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                                <div id=\"testmodal2\" style=\"padding: 5px 20px;\">\r\n");
      out.write("                                    <form id=\"antoform2\" class=\"form-horizontal calender\" role=\"form\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label class=\"col-sm-3 control-label\">Title</label>\r\n");
      out.write("                                            <div class=\"col-sm-9\">\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" id=\"title2\" name=\"title2\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <label class=\"col-sm-3 control-label\">Description</label>\r\n");
      out.write("                                            <div class=\"col-sm-9\">\r\n");
      out.write("                                                <textarea class=\"form-control\" style=\"height:55px;\" id=\"descr2\" name=\"descr\"></textarea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-default antoclose2\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary antosubmit2\">Save changes</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"fc_create\" data-toggle=\"modal\" data-target=\"#CalenderModalNew\"></div>\r\n");
      out.write("                <div id=\"fc_edit\" data-toggle=\"modal\" data-target=\"#CalenderModalEdit\"></div>\r\n");
      out.write("\r\n");
      out.write("                <!-- End Calender modal -->\r\n");
      out.write("                <!-- /page content -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"custom_notifications\" class=\"custom-notifications dsp_none\">\r\n");
      out.write("            <ul class=\"list-unstyled notifications clearfix\" data-tabbed_notifications=\"notif-group\">\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("            <div id=\"notif-group\" class=\"tabbed_notifications\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resource/js/nprogress.js\"></script>\r\n");
      out.write("        <!-- chart js -->\r\n");
      out.write("        <script src=\"resource/js/chartjs/chart.min.js\"></script>\r\n");
      out.write("        <!-- bootstrap progress js -->\r\n");
      out.write("        <script src=\"resource/js/progressbar/bootstrap-progressbar.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/js/nicescroll/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("        <!-- icheck -->\r\n");
      out.write("        <script src=\"resource/js/icheck/icheck.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resource/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resource/js/moment.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/js/calendar/fullcalendar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            $(window).load(function () {\r\n");
      out.write("\r\n");
      out.write("                var date = new Date();\r\n");
      out.write("                var d = date.getDate();\r\n");
      out.write("                var m = date.getMonth();\r\n");
      out.write("                var y = date.getFullYear();\r\n");
      out.write("                var started;\r\n");
      out.write("                var categoryClass;\r\n");
      out.write("\r\n");
      out.write("                var calendar = $('#calendar').fullCalendar({\r\n");
      out.write("                    header: {\r\n");
      out.write("                        left: 'prev,next today',\r\n");
      out.write("                        center: 'title',\r\n");
      out.write("                        right: 'month,agendaWeek,agendaDay'\r\n");
      out.write("                    },\r\n");
      out.write("                    selectable: true,\r\n");
      out.write("                    selectHelper: true,\r\n");
      out.write("                    select: function (start, end, allDay) {\r\n");
      out.write("                        $('#fc_create').click();\r\n");
      out.write("\r\n");
      out.write("                        started = start;\r\n");
      out.write("                        ended = end\r\n");
      out.write("\r\n");
      out.write("                        $(\".antosubmit\").on(\"click\", function () {\r\n");
      out.write("                            var title = $(\"#title\").val();\r\n");
      out.write("                            if (end) {\r\n");
      out.write("                                ended = end\r\n");
      out.write("                            }\r\n");
      out.write("                            categoryClass = $(\"#event_type\").val();\r\n");
      out.write("\r\n");
      out.write("                            if (title) {\r\n");
      out.write("                                calendar.fullCalendar('renderEvent', {\r\n");
      out.write("                                        title: title,\r\n");
      out.write("                                        start: started,\r\n");
      out.write("                                        end: end,\r\n");
      out.write("                                        allDay: allDay\r\n");
      out.write("                                    },\r\n");
      out.write("                                    true // make the event \"stick\"\r\n");
      out.write("                                );\r\n");
      out.write("                            }\r\n");
      out.write("                            $('#title').val('');\r\n");
      out.write("                            calendar.fullCalendar('unselect');\r\n");
      out.write("\r\n");
      out.write("                            $('.antoclose').click();\r\n");
      out.write("\r\n");
      out.write("                            return false;\r\n");
      out.write("                        });\r\n");
      out.write("                    },\r\n");
      out.write("                    eventClick: function (calEvent, jsEvent, view) {\r\n");
      out.write("                        //alert(calEvent.title, jsEvent, view);\r\n");
      out.write("\r\n");
      out.write("                        $('#fc_edit').click();\r\n");
      out.write("                        $('#title2').val(calEvent.title);\r\n");
      out.write("                        categoryClass = $(\"#event_type\").val();\r\n");
      out.write("\r\n");
      out.write("                        $(\".antosubmit2\").on(\"click\", function () {\r\n");
      out.write("                            calEvent.title = $(\"#title2\").val();\r\n");
      out.write("\r\n");
      out.write("                            calendar.fullCalendar('updateEvent', calEvent);\r\n");
      out.write("                            $('.antoclose2').click();\r\n");
      out.write("                        });\r\n");
      out.write("                        calendar.fullCalendar('unselect');\r\n");
      out.write("                    },\r\n");
      out.write("                    editable: true,\r\n");
      out.write("                    events: [\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'All Day Event',\r\n");
      out.write("                            start: new Date(y, m, 1)\r\n");
      out.write("                    },\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'Long Event',\r\n");
      out.write("                            start: new Date(y, m, d - 5),\r\n");
      out.write("                            end: new Date(y, m, d - 2)\r\n");
      out.write("                    },\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'Meeting',\r\n");
      out.write("                            start: new Date(y, m, d, 10, 30),\r\n");
      out.write("                            allDay: false\r\n");
      out.write("                    },\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'Lunch',\r\n");
      out.write("                            start: new Date(y, m, d + 14, 12, 0),\r\n");
      out.write("                            end: new Date(y, m, d, 14, 0),\r\n");
      out.write("                            allDay: false\r\n");
      out.write("                    },\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'Birthday Party',\r\n");
      out.write("                            start: new Date(y, m, d + 1, 19, 0),\r\n");
      out.write("                            end: new Date(y, m, d + 1, 22, 30),\r\n");
      out.write("                            allDay: false\r\n");
      out.write("                    },\r\n");
      out.write("                        {\r\n");
      out.write("                            title: 'Click for Google',\r\n");
      out.write("                            start: new Date(y, m, 28),\r\n");
      out.write("                            end: new Date(y, m, 29),\r\n");
      out.write("                            url: 'http://google.com/'\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
