/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.29
 * Generated at: 2015-12-23 19:00:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prescription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/lib/jstl-1.2.jar", Long.valueOf(1364136296000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <!-- Meta, title, CSS, favicons, etc. -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <title>Metro Medi Care </title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("\r\n");
      out.write("    <link href=\"resource/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <link href=\"resource/fonts/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resource/css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styling plus plugins -->\r\n");
      out.write("    <link href=\"resource/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"resource/css/maps/jquery-jvectormap-2.0.1.css\" />\r\n");
      out.write("    <link href=\"resource/css/icheck/flat/green.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"resource/css/floatexamples.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resource/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resource/js/nprogress.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"nav-md\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container body\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main_container\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 left_col\">\r\n");
      out.write("                <div class=\"left_col scroll-view\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"navbar nav_title\" style=\"border: 0;\">\r\n");
      out.write("                        <a href=\"index.html\" class=\"site_title\"> <span>Metro Medi Care</span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- menu prile quick info -->\r\n");
      out.write("                    <div class=\"profile\">\r\n");
      out.write("                        <div class=\"profile_pic\">\r\n");
      out.write("                            <img src=\"resource/images/user_icon.png\" alt=\"...\" class=\"img-circle profile_img\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"profile_info\">\r\n");
      out.write("                            <span>Welcome,</span>\r\n");
      out.write("                            <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /menu prile quick info -->\r\n");
      out.write("\r\n");
      out.write("                    <br />\r\n");
      out.write("\r\n");
      out.write("                    <!-- sidebar menu -->\r\n");
      out.write("                    \r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- /sidebar menu -->\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- top navigation -->\r\n");
      out.write("            \r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topbar.jsp", out, false);
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- /top navigation -->\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!-- page content  -->\r\n");
      out.write("            <div class=\"right_col\" role=\"main\">\r\n");
      out.write("\t\t\t    <div class=\"\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <div class=\"title_left\">\r\n");
      out.write("                            <h3>Prescriptions <small>Patient Details</small></h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"title_right\">\r\n");
      out.write("                            <div class=\"col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                                    <span class=\"input-group-btn\">\r\n");
      out.write("                            <button class=\"btn btn-default\" type=\"button\">Go!</button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-12 col-sm-12 col-xs-12\">\r\n");
      out.write("                    \t\t<div class=\"x_panel\">\r\n");
      out.write("                                <div class=\"x_title\">\r\n");
      out.write("                                    <h2><i class=\"fa fa-align-left\"></i> Prescriptions / Notes </h2>\r\n");
      out.write("                                    <ul class=\"nav navbar-right panel_toolbox\">\r\n");
      out.write("                                        <li><a class=\"collapse-link\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"dropdown\">\r\n");
      out.write("                                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\"><i class=\"fa fa-wrench\"></i></a>\r\n");
      out.write("                                            <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                                                <li><a href=\"#\">Settings 1</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"#\">Settings 2</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li><a class=\"close-link\"><i class=\"fa fa-close\"></i></a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <div class=\"clearfix\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"x_content\">\r\n");
      out.write("\r\n");
      out.write("                                    <!-- start accordion -->\r\n");
      out.write("                                    <div class=\"accordion\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\r\n");
      out.write("                                        <div class=\"panel\">\r\n");
      out.write("                                            <a class=\"panel-heading\" role=\"tab\" id=\"headingOne\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("                                                <h4 class=\"panel-title\">Prescription note #1</h4>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            \r\n");
      out.write("                                            <div id=\"collapseOne\" class=\"panel-collapse collapse in\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n");
      out.write("                                                <div class=\"panel-body\">\r\n");
      out.write("                                                    <table class=\"table table-bordered\">\r\n");
      out.write("                                                        <thead>\r\n");
      out.write("                                                            <tr>\r\n");
      out.write("                                                                <th>#</th>\r\n");
      out.write("                                                                <th>First Name</th>\r\n");
      out.write("                                                                <th>Last Name</th>\r\n");
      out.write("                                                                <th>Username</th>\r\n");
      out.write("                                                            </tr>\r\n");
      out.write("                                                        </thead>\r\n");
      out.write("                                                        <tbody>\r\n");
      out.write("                                                            <tr>\r\n");
      out.write("                                                                <th scope=\"row\">1</th>\r\n");
      out.write("                                                                <td>Mark</td>\r\n");
      out.write("                                                                <td>Otto</td>\r\n");
      out.write("                                                                <td>@mdo</td>\r\n");
      out.write("                                                            </tr>\r\n");
      out.write("                                                            <tr>\r\n");
      out.write("                                                                <th scope=\"row\">2</th>\r\n");
      out.write("                                                                <td>Jacob</td>\r\n");
      out.write("                                                                <td>Thornton</td>\r\n");
      out.write("                                                                <td>@fat</td>\r\n");
      out.write("                                                            </tr>\r\n");
      out.write("                                                            <tr>\r\n");
      out.write("                                                                <th scope=\"row\">3</th>\r\n");
      out.write("                                                                <td>Larry</td>\r\n");
      out.write("                                                                <td>the Bird</td>\r\n");
      out.write("                                                                <td>@twitter</td>\r\n");
      out.write("                                                            </tr>\r\n");
      out.write("                                                        </tbody>\r\n");
      out.write("                                                    </table>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"panel\">\r\n");
      out.write("                                            <a class=\"panel-heading collapsed\" role=\"tab\" id=\"headingTwo\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                                                <h4 class=\"panel-title\">Prescription note #2</h4>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div id=\"collapseTwo\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingTwo\">\r\n");
      out.write("                                                <div class=\"panel-body\">\r\n");
      out.write("                                                    <p><strong>Collapsible Item 2 data</strong>\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"panel\">\r\n");
      out.write("                                            <a class=\"panel-heading collapsed\" role=\"tab\" id=\"headingThree\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("                                                <h4 class=\"panel-title\">Prescription note #3</h4>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div id=\"collapseThree\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingThree\">\r\n");
      out.write("                                                <div class=\"panel-body\">\r\n");
      out.write("                                                    <p><strong>Collapsible Item 3 data</strong>\r\n");
      out.write("                                                    </p>\r\n");
      out.write("                                                    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- end of accordion -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    \t</div>\r\n");
      out.write("               \t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("                <!-- footer content -->\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("                <!-- /footer content -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("           <!-- /page content -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"custom_notifications\" class=\"custom-notifications dsp_none\">\r\n");
      out.write("        <ul class=\"list-unstyled notifications clearfix\" data-tabbed_notifications=\"notif-group\">\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("        <div id=\"notif-group\" class=\"tabbed_notifications\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- chart js -->\r\n");
      out.write("    <script src=\"resource/js/chartjs/chart.min.js\"></script>\r\n");
      out.write("    <!-- bootstrap progress js -->\r\n");
      out.write("    <script src=\"resource/js/progressbar/bootstrap-progressbar.min.js\"></script>\r\n");
      out.write("    <script src=\"resource/js/nicescroll/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <!-- icheck -->\r\n");
      out.write("    <script src=\"resource/js/icheck/icheck.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"resource/js/custom.js\"></script>\r\n");
      out.write("    <!-- form validation -->\r\n");
      out.write("    <script src=\"resource/js/validator/validator.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
